### ISSUE TITLE
Error while installing shodanx

### ISSUE THREAD

**Issue by hacker01-mika** [sanjai-AK47/ShodanX#6]
i got this while installation shodanx, please help 

[INFO]: Import Error occured in Module imports due to: cannot import name 'XMLParsedAsHTMLWarning' from 'bs4' (/usr/local/lib/python3.11/dist-packages/bs4/__init__.py)
[INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page..

**Comment by sanjai-AK47** [comment]
Hey @hacker01-mika ,
please provide some details from your side and requirements are:
- screenshot of error you are facing
- python version
- version of bs module and you can find the module version using this command: `pip show bs4`
Please provide this details so I can help in resolving this installation issue

**Comment by sanjai-AK47** [comment]
Hey @ilyas-cyber ,
use the command: `pip install appdirs` to resolve this error

**Comment by ilyas-cyber** [comment]
Facing these error bro : 
└─# shodanx
[INFO]: Import Error occured in Module imports due to: cannot import name 'XMLParsedAsHTMLWarning' from 'bs4' (/usr/local/lib/python3.11/dist-packages/bs4/__init__.py)
[INFO]: If you are encountering this issue more than a time please report the issues in ShodanX Github page..

┌──(root㉿DESKTOP-JOVVDJ8)-[/home/ilyas]
└─# pip show bs4
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/shodanx-1.0.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Name: bs4
Version: 0.0.2
Summary: Dummy package for Beautiful Soup (beautifulsoup4)
Home-page:
Author:
Author-email: Leonard Richardson <leonardr@segfault.org>
License: MIT License
Location: /usr/local/lib/python3.11/dist-packages
Requires: beautifulsoup4
Required-by:

**Comment by sanjai-AK47** [comment]
Hey @ilyas-cyber ,
Please check your python version is latest and also install the latest version of bs4 and beautifulsoup4 modules using this command:
`pip install  --upgrade beautifulsoup4
`
`pip install --upgrade bs4`
these are following package required to update but before also install the latest version of python, sorry for the issue the 
shodaX next version will not have this issue .

Kind regards,
@sanjai-AK47

**Comment by ilyas-cyber** [comment]
Thanks mate its works fine any secret tip of extracting origin ips?
